// Generated by tools/update-sitemap.mjs - do not edit by hand.
// Published articles that have a pre-rendered page at /blog/<slug>.html.
window.BLOG_STATIC_SLUGS = [
    "what-is-3d-elevation",
    "business-website-cost-tamil-nadu",
    "choose-web-development-company",
    "static-vs-dynamic-website",
    "website-maintenance-checklist",
    "why-small-businesses-need-a-website",
    "google-business-profile-guide",
    "seo-for-small-businesses",
    "digital-marketing-for-local-businesses",
    "2d-vs-3d-building-design",
    "3d-modeling-before-you-build",
    "2d-drafting-explained",
    "prepare-for-house-plan",
    "website-speed-core-web-vitals",
    "native-vs-cross-platform-apps",
    "custom-software-vs-off-the-shelf",
    "local-seo-basics",
    "ui-vs-ux-difference",
    "plan-a-business-website"
];
