// Generated by tools/update-sitemap.mjs - do not edit by hand.
// Published articles that have a pre-rendered page at /blog/<slug>.html.
window.BLOG_STATIC_SLUGS = [
    "3d-modeling-before-you-build",
    "2d-drafting-explained",
    "prepare-for-house-plan",
    "website-speed-core-web-vitals",
    "native-vs-cross-platform-apps",
    "custom-software-vs-off-the-shelf",
    "local-seo-basics",
    "ui-vs-ux-difference",
    "plan-a-business-website"
];
